[build]
  command = "npm --prefix \"Guía5_20235076\" ci && npm --prefix \"Guía5_20235076\" run build"
  publish = "."

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/Gu%C3%ADa5_20235076/dist/*"
  to = "/Gu%C3%ADa5_20235076/dist/index.html"
  status = 200

[[redirects]]
  from = "/Guía5_20235076/dist/*"
  to = "/Gu%C3%ADa5_20235076/dist/index.html"
  status = 200
